watch:
  - src
  - .trmnlp.yml

variables:
  craft_x_pct: 44
  craft_y_pct: 15
  craft_heading_deg: 339
  moon_y_pct: 16
  distance_earth_km: "410,394"
  distance_moon_km: "14,522"
  speed_kmh: "1,575"
  progress: 100
  updated_at: "2026-04-07 02:04 UTC"
  trail:
    - x: 39
      y: 77
    - x: 39
      y: 76
    - x: 39
      y: 75
    - x: 40
      y: 75
    - x: 40
      y: 75
    - x: 40
      y: 74
    - x: 40
      y: 74
    - x: 41
      y: 73
    - x: 41
      y: 73
    - x: 41
      y: 73
    - x: 42
      y: 72
    - x: 42
      y: 72
    - x: 42
      y: 72
    - x: 43
      y: 72
    - x: 43
      y: 71
    - x: 43
      y: 71
    - x: 44
      y: 71
    - x: 44
      y: 71
    - x: 44
      y: 70
    - x: 45
      y: 70
    - x: 45
      y: 70
    - x: 45
      y: 70
    - x: 46
      y: 70
    - x: 46
      y: 70
    - x: 46
      y: 70
    - x: 47
      y: 69
    - x: 47
      y: 69
    - x: 48
      y: 69
    - x: 48
      y: 69
    - x: 48
      y: 69
    - x: 49
      y: 69
    - x: 49
      y: 69
    - x: 49
      y: 69
    - x: 50
      y: 69
    - x: 50
      y: 69
    - x: 50
      y: 69
    - x: 51
      y: 69
    - x: 51
      y: 69
    - x: 51
      y: 69
    - x: 52
      y: 69
    - x: 52
      y: 69
    - x: 52
      y: 69
    - x: 53
      y: 69
    - x: 53
      y: 69
    - x: 53
      y: 69
    - x: 54
      y: 69
    - x: 54
      y: 69
    - x: 54
      y: 69
    - x: 55
      y: 69
    - x: 55
      y: 69
    - x: 55
      y: 69
    - x: 56
      y: 70
    - x: 56
      y: 70
    - x: 56
      y: 70
    - x: 57
      y: 70
    - x: 57
      y: 70
    - x: 57
      y: 70
    - x: 58
      y: 70
    - x: 58
      y: 71
    - x: 58
      y: 71
    - x: 58
      y: 71
    - x: 59
      y: 71
    - x: 59
      y: 71
    - x: 59
      y: 72
    - x: 59
      y: 72
    - x: 59
      y: 72
    - x: 60
      y: 72
    - x: 60
      y: 73
    - x: 60
      y: 73
    - x: 60
      y: 73
    - x: 60
      y: 73
    - x: 60
      y: 74
    - x: 60
      y: 74
    - x: 60
      y: 74
    - x: 61
      y: 75
    - x: 61
      y: 75
    - x: 61
      y: 76
    - x: 61
      y: 76
    - x: 61
      y: 76
    - x: 61
      y: 77
    - x: 61
      y: 77
    - x: 61
      y: 78
    - x: 62
      y: 78
    - x: 62
      y: 79
    - x: 62
      y: 80
    - x: 62
      y: 81
    - x: 62
      y: 83
    - x: 59
      y: 89
    - x: 39
      y: 86
    - x: 38
      y: 82
    - x: 38
      y: 80
    - x: 38
      y: 79
    - x: 38
      y: 78
    - x: 39
      y: 78
    - x: 39
      y: 77
    - x: 39
      y: 77
    - x: 39
      y: 76
    - x: 39
      y: 76
    - x: 38
      y: 75
    - x: 38
      y: 75
    - x: 38
      y: 74
    - x: 37
      y: 74
    - x: 37
      y: 73
    - x: 37
      y: 73
    - x: 37
      y: 72
    - x: 36
      y: 72
    - x: 36
      y: 71
    - x: 36
      y: 71
    - x: 36
      y: 70
    - x: 36
      y: 70
    - x: 36
      y: 70
    - x: 36
      y: 69
    - x: 35
      y: 69
    - x: 35
      y: 68
    - x: 35
      y: 68
    - x: 35
      y: 68
    - x: 35
      y: 67
    - x: 35
      y: 67
    - x: 35
      y: 66
    - x: 35
      y: 66
    - x: 35
      y: 66
    - x: 35
      y: 65
    - x: 35
      y: 65
    - x: 35
      y: 65
    - x: 35
      y: 64
    - x: 34
      y: 64
    - x: 34
      y: 64
    - x: 34
      y: 63
    - x: 34
      y: 63
    - x: 34
      y: 63
    - x: 34
      y: 62
    - x: 34
      y: 62
    - x: 34
      y: 62
    - x: 34
      y: 61
    - x: 34
      y: 61
    - x: 34
      y: 61
    - x: 34
      y: 61
    - x: 34
      y: 60
    - x: 34
      y: 60
    - x: 34
      y: 60
    - x: 34
      y: 59
    - x: 34
      y: 59
    - x: 34
      y: 59
    - x: 34
      y: 59
    - x: 34
      y: 58
    - x: 34
      y: 58
    - x: 34
      y: 58
    - x: 34
      y: 57
    - x: 34
      y: 57
    - x: 34
      y: 57
    - x: 34
      y: 57
    - x: 34
      y: 56
    - x: 34
      y: 56
    - x: 34
      y: 56
    - x: 34
      y: 56
    - x: 34
      y: 55
    - x: 34
      y: 55
    - x: 34
      y: 55
    - x: 34
      y: 55
    - x: 34
      y: 54
    - x: 34
      y: 54
    - x: 34
      y: 54
    - x: 34
      y: 54
    - x: 34
      y: 53
    - x: 34
      y: 53
    - x: 34
      y: 53
    - x: 34
      y: 53
    - x: 34
      y: 52
    - x: 34
      y: 52
    - x: 34
      y: 52
    - x: 34
      y: 52
    - x: 34
      y: 52
    - x: 34
      y: 51
    - x: 34
      y: 51
    - x: 35
      y: 51
    - x: 35
      y: 51
    - x: 35
      y: 50
    - x: 35
      y: 50
    - x: 35
      y: 50
    - x: 35
      y: 50
    - x: 35
      y: 50
    - x: 35
      y: 49
    - x: 35
      y: 49
    - x: 35
      y: 49
    - x: 35
      y: 49
    - x: 35
      y: 49
    - x: 35
      y: 48
    - x: 35
      y: 48
    - x: 35
      y: 48
    - x: 35
      y: 48
    - x: 35
      y: 47
    - x: 35
      y: 47
    - x: 35
      y: 47
    - x: 35
      y: 47
    - x: 35
      y: 47
    - x: 35
      y: 46
    - x: 35
      y: 46
    - x: 35
      y: 46
    - x: 35
      y: 46
    - x: 35
      y: 46
    - x: 35
      y: 45
    - x: 35
      y: 45
    - x: 36
      y: 45
    - x: 36
      y: 45
    - x: 36
      y: 45
    - x: 36
      y: 45
    - x: 36
      y: 44
    - x: 36
      y: 44
    - x: 36
      y: 44
    - x: 36
      y: 44
    - x: 36
      y: 44
    - x: 36
      y: 43
    - x: 36
      y: 43
    - x: 36
      y: 43
    - x: 36
      y: 43
    - x: 36
      y: 43
    - x: 36
      y: 43
    - x: 36
      y: 42
    - x: 36
      y: 42
    - x: 36
      y: 42
    - x: 36
      y: 42
    - x: 36
      y: 42
    - x: 36
      y: 41
    - x: 36
      y: 41
    - x: 37
      y: 41
    - x: 37
      y: 41
    - x: 37
      y: 41
    - x: 37
      y: 41
    - x: 37
      y: 40
    - x: 37
      y: 40
    - x: 37
      y: 40
    - x: 37
      y: 40
    - x: 37
      y: 40
    - x: 37
      y: 40
    - x: 37
      y: 39
    - x: 37
      y: 39
    - x: 37
      y: 39
    - x: 37
      y: 39
    - x: 37
      y: 39
    - x: 37
      y: 39
    - x: 37
      y: 38
    - x: 37
      y: 38
    - x: 37
      y: 38
    - x: 38
      y: 38
    - x: 38
      y: 38
    - x: 38
      y: 38
    - x: 38
      y: 38
    - x: 38
      y: 37
    - x: 38
      y: 37
    - x: 38
      y: 37
    - x: 38
      y: 37
    - x: 38
      y: 37
    - x: 38
      y: 37
    - x: 38
      y: 36
    - x: 38
      y: 36
    - x: 38
      y: 36
    - x: 38
      y: 36
    - x: 38
      y: 36
    - x: 38
      y: 36
    - x: 38
      y: 36
    - x: 38
      y: 35
    - x: 38
      y: 35
    - x: 39
      y: 35
    - x: 39
      y: 35
    - x: 39
      y: 35
    - x: 39
      y: 35
    - x: 39
      y: 35
    - x: 39
      y: 34
    - x: 39
      y: 34
    - x: 39
      y: 34
    - x: 39
      y: 34
    - x: 39
      y: 34
    - x: 39
      y: 34
    - x: 39
      y: 34
    - x: 39
      y: 33
    - x: 39
      y: 33
    - x: 39
      y: 33
    - x: 39
      y: 33
    - x: 39
      y: 33
    - x: 39
      y: 33
    - x: 40
      y: 33
    - x: 40
      y: 32
    - x: 40
      y: 32
    - x: 40
      y: 32
    - x: 40
      y: 32
    - x: 40
      y: 32
    - x: 40
      y: 32
    - x: 40
      y: 32
    - x: 40
      y: 32
    - x: 40
      y: 31
    - x: 40
      y: 31
    - x: 40
      y: 31
    - x: 40
      y: 31
    - x: 40
      y: 31
    - x: 40
      y: 31
    - x: 40
      y: 31
    - x: 40
      y: 31
    - x: 41
      y: 30
    - x: 41
      y: 30
    - x: 41
      y: 30
    - x: 41
      y: 30
    - x: 41
      y: 30
    - x: 41
      y: 30
    - x: 41
      y: 30
    - x: 41
      y: 30
    - x: 41
      y: 29
    - x: 41
      y: 29
    - x: 41
      y: 29
    - x: 41
      y: 29
    - x: 41
      y: 29
    - x: 41
      y: 29
    - x: 41
      y: 29
    - x: 41
      y: 29
    - x: 41
      y: 28
    - x: 41
      y: 28
    - x: 42
      y: 28
    - x: 42
      y: 28
    - x: 42
      y: 28
    - x: 42
      y: 28
    - x: 42
      y: 28
    - x: 42
      y: 28
    - x: 42
      y: 28
    - x: 42
      y: 27
    - x: 42
      y: 27
    - x: 42
      y: 27
    - x: 42
      y: 27
    - x: 42
      y: 27
    - x: 42
      y: 27
    - x: 42
      y: 27
    - x: 42
      y: 27
    - x: 42
      y: 27
    - x: 42
      y: 26
    - x: 43
      y: 26
    - x: 43
      y: 26
    - x: 43
      y: 26
    - x: 43
      y: 26
    - x: 43
      y: 26
    - x: 43
      y: 26
    - x: 43
      y: 26
    - x: 43
      y: 26
    - x: 43
      y: 25
    - x: 43
      y: 25
    - x: 43
      y: 25
    - x: 43
      y: 25
    - x: 43
      y: 25
    - x: 43
      y: 25
    - x: 43
      y: 25
    - x: 43
      y: 25
    - x: 43
      y: 25
    - x: 43
      y: 24
    - x: 43
      y: 24
    - x: 44
      y: 24
    - x: 44
      y: 24
    - x: 44
      y: 24
    - x: 44
      y: 24
    - x: 44
      y: 24
    - x: 44
      y: 24
    - x: 44
      y: 24
    - x: 44
      y: 24
    - x: 44
      y: 23
    - x: 44
      y: 23
    - x: 44
      y: 23
    - x: 44
      y: 23
    - x: 44
      y: 23
    - x: 44
      y: 23
    - x: 44
      y: 23
    - x: 44
      y: 23
    - x: 44
      y: 23
    - x: 44
      y: 23
    - x: 44
      y: 23
    - x: 45
      y: 22
    - x: 45
      y: 22
    - x: 45
      y: 22
    - x: 45
      y: 22
    - x: 45
      y: 22
    - x: 45
      y: 22
    - x: 45
      y: 22
    - x: 45
      y: 22
    - x: 45
      y: 22
    - x: 45
      y: 22
    - x: 45
      y: 21
    - x: 45
      y: 21
    - x: 45
      y: 21
    - x: 45
      y: 21
    - x: 45
      y: 21
    - x: 45
      y: 21
    - x: 45
      y: 21
    - x: 45
      y: 21
    - x: 45
      y: 21
    - x: 45
      y: 21
    - x: 46
      y: 21
    - x: 46
      y: 21
    - x: 46
      y: 20
    - x: 46
      y: 20
    - x: 46
      y: 20
    - x: 46
      y: 20
    - x: 46
      y: 20
    - x: 46
      y: 20
    - x: 46
      y: 20
    - x: 46
      y: 20
    - x: 46
      y: 20
    - x: 46
      y: 20
    - x: 46
      y: 20
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 19
    - x: 46
      y: 18
    - x: 46
      y: 18
    - x: 46
      y: 18
    - x: 46
      y: 18
    - x: 45
      y: 18
    - x: 45
      y: 18
    - x: 45
      y: 18
    - x: 45
      y: 18
    - x: 45
      y: 18
    - x: 45
      y: 18
    - x: 45
      y: 18
    - x: 45
      y: 18
    - x: 45
      y: 17
    - x: 45
      y: 17
    - x: 45
      y: 17
    - x: 45
      y: 17
    - x: 45
      y: 17
    - x: 45
      y: 17
    - x: 45
      y: 17
    - x: 45
      y: 17
    - x: 45
      y: 16
    - x: 45
      y: 16
    - x: 45
      y: 16
    - x: 45
      y: 16
    - x: 45
      y: 16
    - x: 45
      y: 16
    - x: 45
      y: 16
    - x: 45
      y: 16
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 45
      y: 15
    - x: 44
      y: 15
    - x: 44
      y: 15
    - x: 44
      y: 15
